adapter1   : "AAAAAAAAAAAA"
adapter2   :
rRNA_index : "/data1/pipeline/annotations/rRNA_indexes/hg38_human_rRNA/rRNA_indexes/hg38rRNA"
transcriptome_index : "/data1/pipeline/annotations/trips/homo_sapiens/homo_sapiens_transcriptome_bowtie_indices/gencode_v25_human"
genome_index : "/data1/pipeline/annotations/gwips/homo_sapiens/hg38/hg38_bowtie_indexes/hg38"
genome_fasta : "/data1/pipeline/annotations/gwips/homo_sapiens/hg38/hg38.fa"
annotation_sqlite : "/data1/pipeline/annotations/trips/homo_sapiens/homo_sapiens.Gencode_v25.sqlite"
chrom_sizes_file : "/data1/pipeline/annotations/gwips/homo_sapiens/hg38.chrom.sizes"
skip_trips : "True"
skip_gwips : "False"
